// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/discount.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	models "backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDiscountRepository is a mock of DiscountRepository interface.
type MockDiscountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscountRepositoryMockRecorder
}

// MockDiscountRepositoryMockRecorder is the mock recorder for MockDiscountRepository.
type MockDiscountRepositoryMockRecorder struct {
	mock *MockDiscountRepository
}

// NewMockDiscountRepository creates a new mock instance.
func NewMockDiscountRepository(ctrl *gomock.Controller) *MockDiscountRepository {
	mock := &MockDiscountRepository{ctrl: ctrl}
	mock.recorder = &MockDiscountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscountRepository) EXPECT() *MockDiscountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDiscountRepository) Create(discount *models.Discount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", discount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDiscountRepositoryMockRecorder) Create(discount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDiscountRepository)(nil).Create), discount)
}

// Delete mocks base method.
func (m *MockDiscountRepository) Delete(id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDiscountRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDiscountRepository)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockDiscountRepository) Get(id uint64) (*models.Discount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*models.Discount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDiscountRepositoryMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDiscountRepository)(nil).Get), id)
}

// GetList mocks base method.
func (m *MockDiscountRepository) GetList() ([]models.Discount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList")
	ret0, _ := ret[0].([]models.Discount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockDiscountRepositoryMockRecorder) GetList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockDiscountRepository)(nil).GetList))
}

// GetSpecificList mocks base method.
func (m *MockDiscountRepository) GetSpecificList(instrumentId, userId uint64) ([]models.Discount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpecificList", instrumentId, userId)
	ret0, _ := ret[0].([]models.Discount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpecificList indicates an expected call of GetSpecificList.
func (mr *MockDiscountRepositoryMockRecorder) GetSpecificList(instrumentId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpecificList", reflect.TypeOf((*MockDiscountRepository)(nil).GetSpecificList), instrumentId, userId)
}

// Update mocks base method.
func (m *MockDiscountRepository) Update(id uint64, fieldsToUpdate models.DiscountFieldsToUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, fieldsToUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDiscountRepositoryMockRecorder) Update(id, fieldsToUpdate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDiscountRepository)(nil).Update), id, fieldsToUpdate)
}
